package parkinglotmanagementsystem.fineandpayment.model;

import java.time.LocalDateTime;

public class Fine {

    private int fineId; // Auto-generated by database
    private String plateNumber;
    private String ticketId;
    private FineType fineType;
    private double fineAmount;
    private FineScheme fineScheme; // Scheme used to calculate this fine
    private boolean isPaid;
    private LocalDateTime createdAt;

    public Fine(String plateNumber, String ticketId, FineType fineType,
            double fineAmount, FineScheme fineScheme, LocalDateTime createdAt) {
        this.plateNumber = plateNumber;
        this.ticketId = ticketId;
        this.fineType = fineType;
        this.fineAmount = fineAmount;
        this.fineScheme = fineScheme;
        this.isPaid = false;
        this.createdAt = createdAt;
    }

    public Fine(int fineId, String plateNumber, String ticketId, FineType fineType,
            double fineAmount, FineScheme fineScheme, boolean isPaid, LocalDateTime createdAt) {
        this.fineId = fineId;
        this.plateNumber = plateNumber;
        this.ticketId = ticketId;
        this.fineType = fineType;
        this.fineAmount = fineAmount;
        this.fineScheme = fineScheme;
        this.isPaid = isPaid;
        this.createdAt = createdAt;
    }

    public void markAsPaid() {
        this.isPaid = true;
    }

    // Getters and Setters

    public int getFineId() {
        return fineId;
    }

    public void setFineId(int fineId) {
        this.fineId = fineId;
    }

    public String getPlateNumber() {
        return plateNumber;
    }

    public String getTicketId() {
        return ticketId;
    }

    public FineType getFineType() {
        return fineType;
    }

    public double getFineAmount() {
        return fineAmount;
    }

    public void setFineAmount(double fineAmount) {
        this.fineAmount = fineAmount;
    }

    public FineScheme getFineScheme() {
        return fineScheme;
    }

    public boolean isPaid() {
        return isPaid;
    }

    public void setPaid(boolean paid) {
        isPaid = paid;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Override
    public String toString() {
        return String.format("Fine[ID=%d, Plate=%s, Type=%s, Amount=RM%.2f, Scheme=%s, Paid=%s]",
                fineId, plateNumber, fineType, fineAmount, fineScheme, isPaid ? "Yes" : "No");
    }
}
