package parkinglotmanagementsystem.fineandpayment.model;

import java.time.LocalDateTime;

public class Payment {

    private int paymentId; // Auto-generated by database
    private String ticketId;
    private double parkingFee;
    private double fineAmount;
    private double totalAmount;
    private PaymentMethod paymentMethod;
    private LocalDateTime paymentTime;

    public Payment(String ticketId, double parkingFee, double fineAmount,
            PaymentMethod paymentMethod, LocalDateTime paymentTime) {
        this.ticketId = ticketId;
        this.parkingFee = parkingFee;
        this.fineAmount = fineAmount;
        this.totalAmount = parkingFee + fineAmount;
        this.paymentMethod = paymentMethod;
        this.paymentTime = paymentTime;
    }

    public Payment(int paymentId, String ticketId, double parkingFee, double fineAmount,
            double totalAmount, PaymentMethod paymentMethod, LocalDateTime paymentTime) {
        this.paymentId = paymentId;
        this.ticketId = ticketId;
        this.parkingFee = parkingFee;
        this.fineAmount = fineAmount;
        this.totalAmount = totalAmount;
        this.paymentMethod = paymentMethod;
        this.paymentTime = paymentTime;
    }

    // Getters and Setters

    public int getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

    public String getTicketId() {
        return ticketId;
    }

    public double getParkingFee() {
        return parkingFee;
    }

    public double getFineAmount() {
        return fineAmount;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public LocalDateTime getPaymentTime() {
        return paymentTime;
    }

    @Override
    public String toString() {
        return String.format("Payment[ID=%d, Ticket=%s, Parking=RM%.2f, Fine=RM%.2f, Total=RM%.2f, Method=%s]",
                paymentId, ticketId, parkingFee, fineAmount, totalAmount, paymentMethod);
    }
}
